name: build-and-test-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Instal Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          destribution: 'temurin'

      - name: Install dependies
        run: mvn compile

      - name: Build app
        run: mvn package -DskipTests

      - name: Run test
        run: mvn test
